//BASKET
export const ADDITEMTOBASKET = "ADDITEMTOBASKET";
export const DELETEITEMFROMBASKET = "DELETEITEMFROMBASKET";

//AUTHENTICATE 
export const SIGNINSUCCESS = "SIGNINSUCCESS";
export const SIGNINFAILED = "SIGNINFAILED";
export const SIGNINSTARTED = "SIGNINSTARTED";
export const LOGOUT = "LOGOUT";

//USER
export const SETUSER = "SETUSER";
export const RESETUSER = "RESETUSER";